let DATA, selected=new Set(), quantity=2;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'$'+n.toLocaleString(); const compact=n=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
async function init(){DATA=await fetch('/api/scenario').then(r=>r.json()); renderMap(); renderAll(); bind()}
function renderMap(){const shapes=[["standard_upper","M55 210 A345 190 0 0 1 745 210 L695 235 A295 145 0 0 0 105 235Z"],["premium_upper","M105 235 A295 145 0 0 1 695 235 L650 260 A250 105 0 0 0 150 260Z"],["rear_lower","M150 260 A250 105 0 0 1 650 260 L610 286 A210 72 0 0 0 190 286Z"],["mid_lower","M190 286 A210 72 0 0 1 610 286 L575 310 L225 310Z"],["front_lower","M225 310 L575 310 L540 342 L260 342Z"],["rear_floor","M280 270 L520 270 L520 305 L280 305Z"],["mid_floor","M305 220 L495 220 L495 265 L305 265Z"],["front_floor","M335 165 L465 165 L465 215 L335 215Z"]];let svg='<svg viewBox="0 0 800 410" aria-label="Interactive stadium zone map"><ellipse cx="400" cy="225" rx="365" ry="205" fill="#e8eae4" stroke="#d2d8d1"/>';shapes.forEach(([id,d])=>{let z=DATA.zones.find(x=>x.id===id);svg+=`<path class="zone" data-zone="${id}" d="${d}" fill="${z.color}" opacity=".9"><title>${z.name}: $${z.floor}–$${z.ceiling}</title></path>`});$('#stadium').innerHTML=svg+'</svg>';$('#legend').innerHTML=DATA.zones.map(z=>`<div class="legend-row" data-zone="${z.id}"><i style="background:${z.color}"></i><span>${z.name}</span><small>$${z.floor}–$${z.ceiling}</small></div>`).join('')}
function renderAll(){let s=DATA.summary;$('#metrics').innerHTML=[["REGISTERED FANS",compact(s.fans),"500K synthetic"],["TICKETS REQUESTED",compact(s.tickets_requested),"Across all products"],["AVAILABLE SUPPLY",compact(s.available_supply),`${compact(s.holds)} on hold`],["DEMAND : SUPPLY",s.demand_supply_ratio+'×',"Materially oversubscribed"],["VIP DEMAND",compact(s.vip_demand),"Measured separately"]].map(metric).join('');let max=Math.max(...Object.values(s.demand_by_zone));$('#bars').innerHTML=DATA.zones.map(z=>`<div class="bar"><span>${z.name}</span><div><i style="width:${s.demand_by_zone[z.id]/max*100}%;background:${z.color}"></i></div><b>${compact(s.demand_by_zone[z.id])} / ${compact(z.capacity-z.holds)}</b></div>`).join('');$('#priceEditor').innerHTML=DATA.zones.map(z=>`<div class="price-row"><b>${z.name}</b><input type="range" min="${z.floor}" max="${z.ceiling}" value="${z.price}"><strong>$${z.price}</strong><small>Range $${z.floor}–$${z.ceiling}</small></div>`).join('');let a=DATA.allocation;$('#negMetrics').innerHTML=[["UNFULFILLED",compact(a.unfulfilled_demand),"Qualified demand"],["ELIGIBLE",'81.4K',"Flexible requests"],["RECOVERABLE",compact(a.negotiated_tickets),"Modeled tickets"],["ACCEPTANCE",'37%',"Modeled estimate"],["INCREMENTAL GROSS",'$2.1M',"At approved prices"]].map(metric).join('');$('#conversations').innerHTML=DATA.negotiations.map(n=>`<article class="conversation"><small>REPRESENTATIVE FAN</small><h2>${n.fan}</h2><b>${n.request}</b><div class="bubble">“${n.reply}”</div><span class="status">● ${n.status}</span></article>`).join('');$('#comparison').innerHTML=DATA.comparison.map(x=>`<div class="tr"><span>${x.metric}</span><span>${x.async}</span><span>${x.race}</span></div>`).join('')}
function metric(x){return `<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></div>`}
function bind(){$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-zone]').forEach(e=>e.onclick=()=>toggleZone(e.dataset.zone));$$('#qty button').forEach(b=>b.onclick=()=>{quantity=+b.textContent;$$('#qty button').forEach(x=>x.classList.toggle('active',x===b))});$('#review').onclick=submit;$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('#demo').onclick=()=>{show('fan');toast('Demo started · select zones, then follow the highlighted story')};$$('.price-row input').forEach(i=>i.oninput=()=>{i.nextElementSibling.textContent='$'+i.value;toast('Modeled demand impact updated · price remains inside approved bounds')})}
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
function toggleZone(id){selected.has(id)?selected.delete(id):selected.add(id);$$(`[data-zone="${id}"]`).forEach(e=>e.classList.toggle('selected',selected.has(id)));$('#selectionCount').textContent=selected.size}
async function submit(){if(!selected.size)return toast('Select at least one acceptable zone');let payload={fan:'Alex Rivera',quantity,selections:[...selected],fewer:$('#fewer').checked,alternate:$('#alternate').checked,vip:$('#vip').checked};let r=await fetch('/api/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json());$('#receipt').innerHTML=`<p class="impact"><b>Request saved</b><br>${quantity} tickets · ${selected.size} acceptable zone${selected.size>1?'s':''}. Editable until close.</p>`;toast(r.message)}
async function action(a){let r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})}).then(r=>r.json());let msg=a==='release'?'BEFORE 64,100 → AFTER 67,100 available. Modeled +2,976 fulfilled; +$0.92M gross.':a==='second'?'BEFORE 1 show → AFTER 2 shows. Modeled 58% of flexible demand would consider the new date.':'Clearing complete: policy constraints, seeded lottery, and adjacency applied. Arrival time was excluded.';$('#impact').textContent=msg;toast(a==='clear'?'Market cleared deterministically':'Scenario preview updated')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}init();
